In [ ]:
import pandas as pd
import numpy as np
import re

In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
filepath = '../data/Nairobi propertyprices.csv'
df = pd.read_csv(filepath)

In [ ]:
df.head()

,Price,propertyType,Location,Bedroom,bathroom,House size,Land size
0,KSh 350 000 000,Townhouse,Runda,4.0,4.0,NaN,0.5 acres
1,KSh 30 000 000,Vacant Land,Karen,NaN,NaN,NaN,0.5 acres
2,KSh 325 000 000,Vacant Land,Westlands,NaN,NaN,NaN,0.5 acres
3,KSh 80 000 000,Townhouse,Kitisuru,5.0,5.0,NaN,0.5 acres
4,KSh 25 500 000,Apartment,Kileleshwa,4.0,4.0,230 m²,NaN

In [ ]:
# copy of raw
df_cleaned = df.copy()

###### 1. Clean 'Price' column

In [ ]:
# func

def clean_price(price):
  if pd.isna(price):
    return np.nan
  price_str = re.sub(r"[^\d]", "", price)
  return int(price_str) if price_str else np.nan

In [ ]:
df_cleaned['Price_cleaned'] = df_cleaned['Price'].apply(clean_price)

###### 2. Clean 'House size' column

In [ ]:
re.search(r"(\d+(?:\.\d+)?)", "250 m2").group(1)

def extract_house_size(val):
  if pd.isna(val):
    return np.nan
  match =  re.search(r"(\d+(?:\.\d+)?)", val)
  return float(match.group(1)) if match else np.nan

In [ ]:
df_cleaned['House_size_sqm'] = df_cleaned['House size'].apply(extract_house_size)

###### 3. Clean Land Size

In [ ]:
#0.5 acres

def extract_land_size(val):
  if pd.isna(val):
    return np.nan
  match = re.search(r"(\d+(?:\.\d+)?)", val)
  return float(match.group(1)) if match else np.nan

In [ ]:
df_cleaned['LandSize_acres'] = df_cleaned['Land size'].apply(extract_land_size)

##### 4. Standard and clean 'PropertyType' column

In [ ]:
#df_cleaned['propertyType'].unique()

df_cleaned['propertyType_clean'] = df_cleaned['propertyType'].str.strip().str.title()
df_cleaned['propertyType_clean'] = df_cleaned['propertyType_clean'].replace(
    {
    'Townhuse': 'Townhouse'
    }
)

###### 6. Standard 'Location'

In [ ]:
df_cleaned['Location'] = df_cleaned['Location'].str.strip().str.title()

In [ ]:
df_cleaned.head()

,Price,propertyType,Location,Bedroom,bathroom,House size,Land size,Price_cleaned,House_size_sqm,LandSize_acres,propertyType_clean
0,KSh 350 000 000,Townhouse,Runda,4.0,4.0,NaN,0.5 acres,350000000,NaN,0.5,Townhouse
1,KSh 30 000 000,Vacant Land,Karen,NaN,NaN,NaN,0.5 acres,30000000,NaN,0.5,Vacant Land
2,KSh 325 000 000,Vacant Land,Westlands,NaN,NaN,NaN,0.5 acres,325000000,NaN,0.5,Vacant Land
3,KSh 80 000 000,Townhouse,Kitisuru,5.0,5.0,NaN,0.5 acres,80000000,NaN,0.5,Townhouse
4,KSh 25 500 000,Apartment,Kileleshwa,4.0,4.0,230 m²,NaN,25500000,230.0,NaN,Apartment

##### 8. Drop 'dirty columns' , use cleaned features

In [ ]:
cols_to_drop = ['Price','propertyType','House size','Land size']
df_cleaned.drop(columns=cols_to_drop, inplace=True)

In [ ]:
df_cleaned.columns = ['Location', 'Bedroom', 'bathroom', 'Price', 'House_size_sqm',
       'LandSize_acres', 'propertyType']

In [ ]:
df_cleaned.head()

,Location,Bedroom,bathroom,Price,House_size_sqm,LandSize_acres,propertyType
0,Runda,4.0,4.0,350000000,NaN,0.5,Townhouse
1,Karen,NaN,NaN,30000000,NaN,0.5,Vacant Land
2,Westlands,NaN,NaN,325000000,NaN,0.5,Vacant Land
3,Kitisuru,5.0,5.0,80000000,NaN,0.5,Townhouse
4,Kileleshwa,4.0,4.0,25500000,230.0,NaN,Apartment

##### 💾 save cleaned data

In [ ]:
filepath = '/content/drive/MyDrive/SwiftTraq/Portfolio/019_NairobiRealEstate_Prices/'
df_cleaned.to_csv(filepath+'cleanedNairobi_RE_Prices.csv', index=False)
print("✅ Saved successfully!")

✅ Saved successfully!

###### ©️ 2025 Ochieng Fess | Data Strategist